### ISSUE TITLE
dosbox error

### ISSUE THREAD

**Issue by EhanMMMZET** [almeath/DOSBox-SVN-64-bit-for-macOS#1]
hi, so basically the error that is going on is when i try to run this version of dosbox, it opens but however when i get past the dosbox screen, it crashes. i even ran it in terminal, and this is what it said:

DOSBox version SVN
Copyright 2002-2021 DOSBox Team, published under GNU GPL.
---
CONFIG: Loading primary settings from config file /Users/username/Library/Preferences/DOSBox SVN Preferences
Unable to obtain graphics context for NSWindow (Mojave behavior)
OpenGL extension: pixel_bufer_object 1
Unable to obtain graphics context for NSWindow (Mojave behavior)
dyld: lazy symbol binding failed: Symbol not found: __ZNSt3__113basic_filebufIcNS_11char_traitsIcEEEC1Ev
  Referenced from: /Applications/DOSBox.app/Contents/MacOS/DOSBox
  Expected in: /usr/lib/libc++.1.dylib

dyld: Symbol not found: __ZNSt3__113basic_filebufIcNS_11char_traitsIcEEEC1Ev
  Referenced from: /Applications/DOSBox.app/Contents/MacOS/DOSBox
  Expected in: /usr/lib/libc++.1.dylib

**Comment by almeath** [comment]
Can you please let me know what version of macOS you are running, and on what type of Mac? I built this version on an Intel Mac with Mojave, and have tested it up to and including Sonoma (on Intel Macs).

Have you tried running the self-contained version of the app, inside the linked DMG archive? That version should not rely on anything in your usr/lib folder to run - all the necessary dylib files are bundled inside the app package.

**Comment by EhanMMMZET** [comment]
macOS 10.15.7, and on a iMac from 2013 and also i tried to run the self-contained one but it says its broken and cant be run

**Comment by EhanMMMZET** [comment]
additionally, i have run versions of dosbox in the past and they all worked, so i'm not sure why they dont work anymore

**Comment by almeath** [comment]
> macOS 10.15.7, and on a iMac from 2013 and also i tried to run the self-contained one but it says its broken and cant be run

After macOS 10.14 Apple started progressively locking down the macOS. It treats many unsigned and modified/customized apps as potentially dangerous, and so it tends to say they are "broken" when it in fact they are perfectly OK. If you encounter that erroneous error message, you should try the following:

1. Open the Terminal
2. Type the following:

xattr -cr

Follow this by pressing the space bar, and then drag the DOSBox app into your terminal window, which will add its path to the command. Then press "return".

That should strip the DOSBox app of any extended attributes which your macOS has placed on the app, leaving it in a completely clean state, which should then allow it to run.

In addition, the first time you run the app, right-click on it, and select to open it from the contextual menu (rather than double-clicking the app to open it). This bypasses Apple's gatekeeper feature, or should at least allow you to select to "open the file anyway", even if the macOS reports it as broken or damaged.

Please let me know if the above steps allow you to open the "self-contained" version (i.e. the one with all the dylib support files inside the app bundle.

**Comment by EhanMMMZET** [comment]
it worked, thanks for the swift replies and the help

**Comment by almeath** [comment]
No problem at all .. I am glad it worked for you. Apple has complicated things with its security changes, but these work-around techniques are still holding even under Sonoma. Hopefully it won't get any more onerous than it already is.
